define({
    error: 'Tiles Manager Error',
    button_label: 'Téléchargement en gros',
    ghg_title: 'Gaz à effet de serre',
    ghg_description: 'Applications liées à GES',
    ghg_button: 'Aller au module de gaz à effet de serre',
    std_title: 'Outils d\'analyse statistique',
    std_description: 'Fonctions statistiques et utilitaires',
    std_button: 'Aller au module d\'analyse',
    ghg_overview: 'Aperçu régional',
    ghg_overview_description: 'Description de l\'aperçu régional',
    ghg_overview_button: 'Aller au module',
    ghg_quality: 'AQ-CQ et vérification',
    ghg_quality_description: 'Description de AQ-CQ',
    ghg_quality_button: 'Aller au module',
    ghg_indicators: 'Indicateurs',
    ghg_indicators_description: 'Description de indicateurs',
    ghg_indicators_button: 'Aller au module',
    ghg_spatial_download: 'Télécharger données géoréférencées',
    ghg_spatial_download_description: 'Description téléchargement spatiale',
    ghg_spatial_download_button: 'Aller au module',
    ghg_spatial_browse: 'Explorer données géoréférencées',
    ghg_spatial_browse_description: 'Description de données géoréférencées',
    ghg_spatial_browse_button: 'Aller au module',
    no_data_to_display: 'Aucune donnée à afficher',
    please_make_another_selection: 'S\'il vous plaît effectuez une autre sélection'
});
