define({
    error: 'Tiles Manager Error',
    module_button_label: 'Aller au module',
    button_label: 'Téléchargement en gros',
    ghg_title: 'Outils d\'analyse de émissions',
    ghg_description: 'Applications liées à GES',
    ghg_button: 'Aller au module de gaz à effet de serre',
    std_title: 'Outils d\'analyse statistique',
    std_description: 'Fonctions statistiques et utilitaires',
    std_button: 'Aller au module d\'analyse',
    ghg_overview: 'Aperçu régional',
    ghg_overview_description: 'L\'outil donne aux l\'utilisateurs un aperçu des émissions provenant des secteurs de l\'agriculture et de l\'utilisation des terres pour un ou plusieurs pays, ainsi que la possibilité de comparer les résultats avec la région (ou bien les régions) et continent (ou bien les continents) correspondantes, et le monde.',
    ghg_overview_button: 'Aller au module',
    ghg_quality: 'AQ-CQ et vérification',
    ghg_quality_description: 'L\'outil permet aux utilisateurs de comparer les émissions et les données d\'activité des secteurs agriculture et utilisation des terres rapportées par les pays dans les communications nationales à la CCNUCC, avec la base de données sur les émissions de FAOSTAT.',
    ghg_quality_button: 'Aller au module',
    ghg_indicators: 'Indicateurs',
    ghg_indicators_description: 'L\'outil permet aux utilisateurs d\'analyser des indicateurs d\'émissions, exprimés en intensité de carbone par unité de produit et productivité, au niveau national et régional. L’outil utilise les données FAOSTAT et offre un niveau d\'analyse détaillé, tout en facilitant les comparaisons entre pays et régionaux.',
    ghg_indicators_button: 'Aller au module',
    ghg_spatial_download: 'Télécharger données géoréférencées',
    ghg_spatial_download_description: 'L\'outil permet aux utilisateurs d’accéder et examiner des données géoréférencées globales utilisées dans la base de données sur les émissions de FAOSTAT pour estimer les émissions de catégories spécifiques de l\'agriculture et de l\'utilisation des terres. Les données sont téléchargeables au niveau des pays.',
    ghg_spatial_download_button: 'Aller au module',
    ghg_spatial_browse: 'Explorer données géoréférencées',
    ghg_spatial_browse_description: 'L\'outil permet aux utilisateurs d’accéder et examiner des données géoréférencées globales utilisées dans la base de données sur les émissions de FAOSTAT pour estimer les émissions de catégories spécifiques de l\'agriculture et de l\'utilisation des terres. Les données sont téléchargeables au niveau des pays.',
    ghg_spatial_browse_button: 'Aller au module',
    ghg_spatial: 'Données Géoréférencées',
    ghg_spatial_description: 'L\'outil permet aux utilisateurs d’accéder et examiner des données géoréférencées globales utilisées dans la base de données sur les émissions de FAOSTAT pour estimer les émissions de catégories spécifiques de l\'agriculture et de l\'utilisation des terres. Les données sont téléchargeables au niveau des pays.',

});
