define({
    error: 'Error gestor mosaicos',
    module_button_label: 'Ir al módulo',
    button_label: 'Descarga de grandes cantidades de datos',
    ghg_title: 'Gases de efecto invernadero',
    ghg_description: 'Aplicaciones relacionadas con GEI',
    ghg_button: 'Ir al módulo de gases de efecto invernadero',
    std_title: 'Herramientas de análisis estadísticos',
    std_description: 'Funciones estadísticas y utilidades',
    std_button: 'Ir al módulo de análisis',
    ghg_overview: 'Panorama regional',
    ghg_overview_description: 'Descripción del panorama regional',
    ghg_overview_button: 'Ir al módulo',
    ghg_quality: 'GC-CC y verificación',
    ghg_quality_description: 'Descripción de GC/CC',
    ghg_quality_button: 'Ir al módulo',
    ghg_indicators: 'Indicadores',
    ghg_indicators_description: 'Descripción de indicadores.',
    ghg_indicators_button: 'Ir al módulo',
    ghg_spatial_download: 'Descargar datos georreferenciados',
    ghg_spatial_download_description: 'Descripción de descargas espaciales.',
    ghg_spatial_download_button: 'Ir al módulo',
    ghg_spatial_browse: 'Visualizar datos georreferenciados',
    ghg_spatial_browse_description: 'Descripción de datos georreferenciados',
    ghg_spatial_browse_button: 'Ir al módulo',
    no_data_to_display: 'No hay datos para mostrar',
    please_make_another_selection: 'Por favor haga otra selección'
});