define({
    error: 'Error gestor mosaicos',
    module_button_label: 'Ir al módulo',
    button_label: 'Descarga de grandes cantidades de datos',
    ghg_title: 'Herramientas de análisis de emisiones',
    ghg_description: 'Aplicaciones relacionadas con GEI',
    ghg_button: 'Ir al módulo de gases de efecto invernadero',
    std_title: 'Herramientas de análisis estadísticos',
    std_description: 'Funciones estadísticas y utilidades',
    std_button: 'Ir al módulo de análisis',
    ghg_overview: 'Panorama regional',
    ghg_overview_description: 'La herramienta ofrece a los usuario una visión general de las emisiones de los sectores de la agricultura y el uso de la tierra para uno o más países, así como la posibilidad de comparar los resultados con la(s) región(es) y continente(s) correspondientes, y el mundo.',
    ghg_overview_button: 'Ir al módulo',
    ghg_quality: 'GC-CC y verificación',
    ghg_quality_description: 'La herramienta permite a los usuarios comparar las emisiones y los datos de actividad para los sectores de la agricultura y el uso de la tierra reportados por los países en las comunicaciones nacionales a la CMNUCC, con los datos de la base de datos de Emisiones de FAOSTAT.',
    ghg_quality_button: 'Ir al módulo',
    ghg_indicators: 'Indicadores',
    ghg_indicators_description: 'La herramienta permite a los usuarios analizar los indicadores de emisiones, expresados como la intensidad de carbono por unidad de producto de un producto básico dado, contra la productividad a nivel nacional y regional. Ésta usa información basada en los datos de FAOSTAT, proporcionando un nivel detallado de análisis, al tiempo que facilita las comparaciones entre países y a nivel regional.',
    ghg_indicators_button: 'Ir al módulo',
    ghg_spatial_download: 'Descargar datos georreferenciados',
    ghg_spatial_download_description: 'La herramienta permite a los usuarios acceder y examinar datos georreferenciados globales utilizados en la base de datos de Emisiones de FAOSTAT para estimar las emisiones de categorías específicas de la agricultura y el uso de la tierra. Los datos descargables a nivel nacional.',
    ghg_spatial_download_button: 'Ir al módulo',
    ghg_spatial_browse: 'Visualizar datos georreferenciados',
    ghg_spatial_browse_description: 'La herramienta permite a los usuarios acceder y examinar datos georreferenciados globales utilizados en la base de datos de Emisiones de FAOSTAT para estimar las emisiones de categorías específicas de la agricultura y el uso de la tierra. Los datos descargables a nivel nacional.',
    ghg_spatial_browse_button: 'Ir al módulo',
    ghg_spatial: 'Datos Georreferenciados',
    ghg_spatial_description: 'La herramienta permite a los usuarios acceder y examinar datos georreferenciados globales utilizados en la base de datos de Emisiones de FAOSTAT para estimar las emisiones de categorías específicas de la agricultura y el uso de la tierra. Los datos descargables a nivel nacional.',

});