define({
    root : {
        error: 'Tiles Manager Error',
        button_label: 'Bulk Downloads',
        module_button_label: 'Go to the module',
        ghg_title: 'Emissions Analysis Tools',
        ghg_description: 'Applications related to GHG',
        ghg_button: 'Go to the Greenhouse Gases Module',
        std_title: 'Statistical Analysis Tools',
        std_description: 'Statistical functions and utilities',
        std_button: 'Go to the Analysis Module',
        ghg_overview: 'Regional Overview',
        ghg_overview_description: 'The tool gives users an overview of emissions from the agriculture and land use sectors for one or more countries, as well as the option to compare the results with the corresponding region(s), continent(s), and the world.',
        ghg_overview_button: 'Go to the Regional Overview module',
        ghg_quality: 'QA-QC and Verification',
        ghg_quality_description: 'The tool allows users to compare emissions and activity data for the agriculture and land use sectors reported by country to the UNFCCC in National Communications with data from FAOSTAT Emissions database.',
        ghg_quality_button: 'Go to the QA-QC and Verification module',
        ghg_indicators: 'Indicators',
        ghg_indicators_description: 'The tool allows users to analyze emissions indicators, expressed as carbon intensity per unit product of a given commodity, against productivity at country and regional level. Using information based on FAOSTAT data, it provides a detailed level of analysis, while facilitating country and regional-level comparisons.',
        ghg_indicators_button: 'Go to the Indicators module',
        ghg_spatial_download: 'Download Georeferenced Data',
        ghg_spatial_download_description: 'The tool allows users to access and examine global georeferenced data used to estimate emissions of specific agriculture and land use categories in the FAOSTAT Emissions database. The data are available for download at country level.',
        ghg_spatial_download_button: 'Go to the Download Georeferenced Data module',
        ghg_spatial_browse: 'Browse Georeferenced Data',
        ghg_spatial_browse_description: 'The tool allows users to access and examine global georeferenced data used to estimate emissions of specific agriculture and land use categories in the FAOSTAT Emissions database. The data are available for download at country level.',
        ghg_spatial_browse_button: 'Go to the Browse Georeferenced Data module',
        ghg_spatial: 'Georeferenced Data',
        ghg_spatial_description: ''
    },
    F : true,
    S : true
});